unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

set -g default-shell /usr/bin/fish
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Leader: Ctrl+s
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Vim-style pane switching
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Split panes in current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Sane defaults
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g set-clipboard on
setw -g mode-keys vi
set -g status-position top
set -g detach-on-destroy off
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -sg escape-time 0
set -g focus-events on
set -g allow-passthrough on
setw -g aggressive-resize on
bind c new-window -c "#{pane_current_path}"

# Catppuccin 
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
 
# Statusbar 
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"


# set -g status-style "bg=default,fg=default"
# set -g status-left "#[fg=black,bg=blue,bold] #S #[bg=default] "
# set -g status-right "#[fg=blue]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
# set -g window-status-format "#[fg=brightblack] #I:#W "
# set -g window-status-current-format "#[fg=blue,bold] #I:#W "
# set -g pane-border-style "fg=brightblack"
# set -g pane-active-border-style "fg=blue"
# set -g message-style "bg=default,fg=blue"
# set -g message-command-style "bg=default,fg=blue"
# set -g mode-style "bg=blue,fg=black"
# setw -g clock-mode-colour blue

